name: mobo_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.2  
  logger: ^2.0.2+1
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  readmore: ^2.2.0
  http: ^1.1.2
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0

   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/product/
    - lib/assets/banners/
    - lib/assets/Rooms/
    - lib/assets/avatars/
    - lib/assets/markets/
    
  fonts: 
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Poppins-Bold.ttf
          weight: 800