name: mobo_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.2  
  logger: ^2.0.2+1
  intl: ^0.19.0
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  readmore: ^2.2.0
  # http: ^1.1.2
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_rating_bar: ^4.0.1
  dio: ^5.4.0
  lottie: ^2.7.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/Mobo.png' 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/product/
    - assets/banners/
    - assets/Rooms/
    - assets/avatars/
    - assets/markets/
    - assets/social/
    - assets/animations/

    
  fonts: 
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800